# Generated by Django 5.0.2 on 2024-02-20 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('main_category', models.CharField(choices=[('OPERATING', 'Operating'), ('INVENTORY', 'Inventory'), ('LABOUR', 'Labour'), ('OTHERS', 'Others')])),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CREDITCARD', 'Credit Card'), ('DEBITCARD', 'Debit Card')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(unique=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CREDITCARD', 'Credit Card'), ('DEBITCARD', 'Debit Card')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_income', to=settings.AUTH_USER_MODEL)),
                ('deposit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='main.incomeaccount')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='main.incomecategory')),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='main.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('default_expense_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payees_with_default', to='main.expensecategory')),
                ('default_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payees_with_default', to='main.paymentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('unpaid', 'Unpaid')], max_length=10)),
                ('total_amount', models.IntegerField()),
                ('main_category', models.CharField(choices=[('OPERATING', 'Operating'), ('INVENTORY', 'Inventory'), ('LABOUR', 'Labour'), ('OTHERS', 'Others')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses_receipts/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='main.expensecategory')),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='main.outlet')),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='main.payee')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='main.paymentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('outlets', models.ManyToManyField(related_name='authorized_user_profiles', to='main.outlet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
